sudo: required
services:
    - docker

before_install:
    - docker build -t coffeesam/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run coffeesam/react-test npm test -- --coverage

after_success:
    - docker build -t coffeesam/multi-client ./client
    - docker build -t coffeesam/multi-nginx ./nginx
    - docker build -t coffeesam/multi-server ./server
    - docker build -t coffeesam/multi-worker ./worker

    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push coffeesam/multi-client
    - docker push coffeesam/multi-nginx
    - docker push coffeesam/multi-server
    - docker push coffeesam/multi-worker